echo "Content-Type: text/plain"
echo ""
case $1 in
  AUTH_TYPE) echo "$AUTH_TYPE";;
  CONTENT_LENGTH) echo "$CONTENT_LENGTH";;
  CONTENT_TYPE) echo "$CONTENT_TYPE";;
  GATEWAY_INTERFACE) echo "$GATEWAY_INTERFACE";;
  PATH_INFO) echo "$PATH_INFO";;
  PATH_TRANSLATED) echo "$PATH_TRANSLATED";;
  QUERY_STRING) echo "$QUERY_STRING";;
  REMOTE_ADDR) echo "$REMOTE_ADDR";;
  REMOTE_HOST) echo "$REMOTE_HOST";;
  REMOTE_IDENT) echo "$REMOTE_IDENT";;
  REMOTE_USER) echo "$REMOTE_USER";;
  REQUEST_METHOD) echo "$REQUEST_METHOD";;
  SCRIPT_NAME) echo "$SCRIPT_NAME";;
  SERVER_NAME) echo "$SERVER_NAME";;
  SERVER_PORT) echo "$SERVER_PORT";;
  SERVER_PROTOCOL) echo "$SERVER_PROTOCOL";;
  SERVER_SOFTWARE) echo "$SERVER_SOFTWARE";;
esac
